services:
  - type: web
    name: evisitors-backend
    runtime: node
    plan: free
    rootDir: attendance-backend-main
    buildCommand: npm install && npm run build
    startCommand: npm run start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        value: https://evisitors-frontend.onrender.com
      - key: DATABASE_URL
        value: postgresql://evisitors_user:RK0uvG8ZSkHH551BH2GZ7YWqtE25q37l@dpg-d8h6vtddt1ts7383hlu0-a.oregon-postgres.render.com/evisitors
      - key: COOKIE_DOMAIN
        value: .onrender.com
      - key: FORCE_DB_SYNC
        value: "true"


  - type: web
    name: evisitors-frontend
    runtime: node
    plan: free
    rootDir: E-visitors-main
    buildCommand: npm install && npm run build
    startCommand: npx serve dist -l $PORT
    envVars:
      - key: VITE_API_URL
        value: https://evisitors-backend.onrender.com
      - key: VITE_APP_URL
        value: https://evisitors-frontend.onrender.com
